module.exports = {


	//Tune constants
	PLAY: 'PLAY',
	PAUSE: 'PAUSE',
	NEXT: 'NEXT',
	PREV: 'PREV',

	CHANGE_EVENT_TUNE: 'CHANGE',



	//Ux constants
	SEARCH: 'SEARCH',
	PLAYLIST_SHOW: 'PLAYLIST_1',
	PLAYLIST_HIDE: 'PLAYLIST_0',
	SEARCH_SHOW: 'SEARCH_1',
	SEARCH_HIDE: 'SEARCH_0',
	DROPDOWN_SHOW: 'DROPDOWN_1',
	DROPDOWN_HIDE: 'DROPDOWN_0',
	VIEW_SIZE_LARGE: 'VIEW_SIZE_0',
	VIEW_SIZE_NORMAL: 'VIEW_SIZE_1',
	VIEW_SIZE_LARGE: 'VIEW_SIZE_3',
	VOLUME_SHOW: 'VOLUME_1',
	VOLUME_HIDE: 'VOLUME_0',
	UX_CONTROLS_SHOW: 'UX_CONTROLS_1',
	UX_CONTROLS_HIDE: 'UX_CONTROLS_0',
	TRACK_THUMB_SHOW: 'TRACK_THUMB_1',
	TRACK_THUMB_HIDE: 'TRACK_THUMB_0',
	ASPECT: 'ASPECT',
	POSITION: 'POSITION',
	VOLUME: 'VOLUME',

	CHANGE_EVENT_UX: 'TRANSFORM'
};