module.exports = {


	//Tune constants
	PLAY: 'PLAY',
	PAUSE: 'PAUSE',
	NEXT: 'NEXT',
	PREV: 'PREV',
	SEEK: 'SEEK',

	CHANGE_EVENT_TUNE: 'CHANGE',


	//adapters
	REGISTER_ADAPTER: 'R_ADAPTER',
	ACTIVATE_ADAPTER: 'A_ADAPTER',

	//Ux constants
	SEARCH: 'SEARCH',
	PLAYLIST_SHOW: 'PLAYLIST_1',
	PLAYLIST_HIDE: 'PLAYLIST_0',
	SEARCH_SHOW: 'SEARCH_1',
	SEARCH_HIDE: 'SEARCH_0',
	DROPDOWN_SHOW: 'DROPDOWN_1',
	DROPDOWN_HIDE: 'DROPDOWN_0',
	VIEW_SIZE_SMALL: 'VIEW_SIZE_0',
	VIEW_SIZE_NORMAL: 'VIEW_SIZE_1',
	VIEW_SIZE_LARGE: 'VIEW_SIZE_3',
	SIZE_COLLAPSE_SHOW: 'SC_1',
	SIZE_COLLAPSE_HIDE: 'SC_0',
	VOLUME_SHOW: 'VOLUME_1',
	VOLUME_HIDE: 'VOLUME_0',
	UX_CONTROLS_SHOW: 'UX_CONTROLS_1',
	UX_CONTROLS_HIDE: 'UX_CONTROLS_0',
	TRACK_THUMB_SHOW: 'TRACK_THUMB_1',
	TRACK_THUMB_HIDE: 'TRACK_THUMB_0',
	ASPECT: 'ASPECT',
	POSITION: 'POSITION',
	VOLUME: 'VOLUME',

	CHANGE_EVENT_UX: 'TRANSFORM',


	LOCAL_STORAGE_UX_STATE_KEY: 'ux_state',
	LOCAL_STORAGE_TUNE_STATE_KEY: 'tune_state'
};